---
title: ""
header-includes:
  - \usepackage[T1]{fontenc}
  - \usepackage[scaled]{berasans}
  - \usepackage{wrapfig}
  - \renewcommand*\familydefault{\sfdefault}
output: pdf_document
fontsize: 12pt
classoption: [landscape]
---
```{r setup, echo = FALSE, include = FALSE}
# Load libraries
library(dplyr)            # Data frame operations
library(jsonlite)         # JSON operations
library(janitor)          # Cleaning operations
library(lubridate)        # Date/time operations
library(ggplot2)          # Plotting operations
library(data.table)       # rbindlist
library(ggthemes)         # ggplot2 themes
library(scales)           # scaling numbers

knitr::opts_chunk$set(
  eval = T,
  echo = F,
  include = F,
  warning = F,
  message = F,
  error = F,
  include = T
  )


```

```{r load-data}
# Load streaming data

streaming_data <- fromJSON(txt = "data.json") %>%
  as_tibble %>%
  clean_names %>% 
  mutate(
    end_time = as.POSIXct(end_time),
    end_date = as.Date(end_time)
  )

# Cleanse data

streaming_data_cleaned <- streaming_data %>% 
  mutate(
    end_time = as.POSIXct(end_time)
  )

colours <- c("#1DB954", "#1F7062", "#1D382F", "#B3E251", "#40C8B1", "#FFFFFF",
  "#191414"
  )

```

<!-- Title page -->

```{r title-page, child = "pages/title_page.Rmd"}
```

<!-- Table of contents -->
```{r toc, child = "pages/toc.Rmd"}
```

<!-- Preface -->
```{r preface, child = "pages/preface.Rmd"}
```

<!-- page 1 -->
```{r page-1, child = "pages/page_1.Rmd"}
```


```{r}

streaming_data_cleaned %>% 
  mutate(
    hour = hour(end_time)
  ) %>% 
  group_by(hour) %>%
  summarise(minutes_played = sum(ms_played) / 1000 / 60) %>%
  ggplot() +
  geom_line(mapping = aes(x = hour, y = minutes_played))

```

```{r}

streaming_data_cleaned %>% 
  .$artist_name %>% 
  unique %>% 
  length

```

```{r}
streaming_data_cleaned %>% 
  .$track_name %>%
  unique %>%
  length

```

```{r}

streaming_data_cleaned %>% 
  group_by(artist_name) %>% 
  summarise(minutes_played = sum(ms_played) / 1000 / 60) %>%
  arrange(desc(minutes_played)) %>%
  head(20) %>% 
  ggplot() +
  geom_col(mapping = aes(y = reorder(artist_name, minutes_played), x = minutes_played))
```

```{r}

streaming_data_cleaned %>% 
  group_by(artist_name) %>% 
  summarise(listens = n()) %>%
  arrange(desc(listens)) %>%
  head(20) %>% 
  ggplot() +
  geom_col(mapping = aes(y = reorder(artist_name, listens), x = listens))
```

```{r}

streaming_data_cleaned %>% 
  group_by(artist_name, track_name) %>% 
  summarise(minutes_played = sum(ms_played) / 1000 / 60, track = first(paste(track_name, artist_name, sep = " - "))) %>%
  arrange(desc(minutes_played)) %>%
  head(20) %>% 
  ggplot() +
  geom_col(mapping = aes(y = reorder(track, minutes_played), x = minutes_played))
```

```{r}

streaming_data_cleaned %>% 
  group_by(artist_name, track_name) %>% 
  summarise(listens = n(), track = first(paste(track_name, artist_name, sep = " - "))) %>%
  arrange(desc(listens)) %>%
  head(20) %>% 
  ggplot() +
  geom_col(mapping = aes(y = reorder(track, listens), x = listens))
```

```{r fig.width = 15}

streaming_data_cleaned %>% 
  mutate(
    date = as.Date(end_time),
    hour = hour(end_time),
  ) %>% 
  group_by(date, hour) %>%
  summarise(minutes_played = sum(ms_played) / 1000 / 60) %>% 
  left_join(
    min(as.Date(streaming_data_cleaned$end_time)):max(as.Date(streaming_data_cleaned$end_time)) %>% 
      as.Date(origin = "1970-01-01") %>% 
      lapply(function(x) {
        tibble(
          date = x,
          hour = 0:23,
        )
      }) %>% 
      rbindlist %>% 
      as_tibble,
    .,
    by = c("date", "hour")
  ) %>% 
  mutate(
    minutes_played = ifelse(is.na(minutes_played), 0, minutes_played)
  ) %>% 
  #filter(month(date) == 3) %>% 
  ggplot() +
  #stat_density2d()
  geom_tile(
    mapping = aes(x = date, y = hour, fill = minutes_played)
  )

```